FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r api/requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "api/frontend/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
